# Generated by Django 5.2.4 on 2025-07-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='category',
        ),
        migrations.AddField(
            model_name='professional',
            name='categories',
            field=models.ManyToManyField(to='professionals.category', verbose_name='Categorías'),
        ),
    ]
